import os
import sys
import time

# 配置路径
INGREDIENTS_DIR = "Clash/Ingredients/AdBlock"
OUTPUT_FILE = "Clash/Outputs/MergedADBan.list"

def log(msg):
    print(f"[*] {msg}", flush=True)

def parse_rule(line):
    """解析单行规则，返回 (类型, 值)"""
    line = line.strip()
    if not line or line.startswith("#"):
        return None, None
    
    parts = line.split(",")
    if len(parts) >= 2:
        return parts[0].upper(), parts[1].strip()
    return None, None

def build():
    log("Starting Smart Build System...")
    start_time = time.time()
    
    all_rules = set()
    raw_count = 0
    
    # 1. 扫描素材
    if not os.path.exists(INGREDIENTS_DIR):
        log(f"Error: Directory {INGREDIENTS_DIR} not found.")
        return

    for filename in os.listdir(INGREDIENTS_DIR):
        if filename.endswith(".list"):
            file_path = os.path.join(INGREDIENTS_DIR, filename)
            log(f"Reading ingredient: {filename}")
            with open(file_path, "r", encoding="utf-8") as f:
                for line in f:
                    raw_count += 1
                    rtype, rval = parse_rule(line)
                    if rtype and rval:
                        # 存储为 (类型, 值) 的元组，方便去重
                        all_rules.add((rtype, rval))

    unique_count = len(all_rules)
    log(f"Ingested {raw_count} raw lines. Found {unique_count} unique rules.")

    # 2. 逻辑优化 (简单去重后排序)
    # 按规则类型和域名排序，方便人类阅读和 Clash 批量处理
    sorted_rules = sorted(list(all_rules), key=lambda x: (x[0], x[1]))

    # 3. 写入输出
    log(f"Writing to {OUTPUT_FILE}...")
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# --------------------------------------------------------------\n")
        f.write(f"# ACL4SSR-Neo Merged AD Block List\n")
        f.write(f"# Generated by Smart Build System at {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"# Total Rules: {unique_count}\n")
        f.write("# --------------------------------------------------------------\n\n")
        
        for rtype, rval in sorted_rules:
            f.write(f"{rtype},{rval}\n")

    duration = time.time() - start_time
    log(f"Build completed in {duration:.2f} seconds.")
    log(f"Final output: {OUTPUT_FILE}")

if __name__ == "__main__":
    try:
        build()
    except Exception as e:
        log(f"Fatal Error: {str(e)}")
        sys.exit(1)
