import os
import sys
import time

# 配置路径
INGREDIENTS_DIR = "Clash/Ingredients/AdBlock"
OUTPUT_FILE = "Clash/Outputs/MergedADBan.list"
RULE_PRIORITY = {
    "DOMAIN": 50,
    "DOMAIN-SUFFIX": 40,
    "DOMAIN-KEYWORD": 30,
    "IP-CIDR": 20,
    "IP-CIDR6": 20,
}


def log(msg):
    print(f"[*] {msg}", flush=True)


def parse_rule(line):
    """解析单行规则，返回 (类型, 值)"""
    line = line.strip()
    if not line or line.startswith("#"):
        return None, None

    parts = line.split(",")
    if len(parts) >= 2:
        return parts[0].upper(), parts[1].strip()
    return None, None


def pick_preferred_rule_type(rule_types):
    return max(rule_types, key=lambda rule_type: (RULE_PRIORITY.get(rule_type, 0), rule_type))


def build():
    log("Starting Smart Build System...")
    start_time = time.time()

    rules_by_value = {}
    raw_count = 0

    # 1. 扫描素材
    if not os.path.exists(INGREDIENTS_DIR):
        log(f"Error: Directory {INGREDIENTS_DIR} not found.")
        return

    for filename in os.listdir(INGREDIENTS_DIR):
        if filename.endswith(".list"):
            file_path = os.path.join(INGREDIENTS_DIR, filename)
            log(f"Reading ingredient: {filename}")
            with open(file_path, "r", encoding="utf-8") as f:
                for line in f:
                    raw_count += 1
                    rtype, rval = parse_rule(line)
                    if rtype and rval:
                        rules_by_value.setdefault(rval, set()).add(rtype)

    deduped_rules = set()
    conflict_map = {}
    for rval, rule_types in rules_by_value.items():
        if len(rule_types) > 1:
            winner = pick_preferred_rule_type(rule_types)
            conflict_map[rval] = {
                "winner": winner,
                "rule_types": sorted(rule_types),
            }
            deduped_rules.add((winner, rval))
        else:
            deduped_rules.add((next(iter(rule_types)), rval))

    unique_count = len(deduped_rules)
    conflict_count = len(conflict_map)
    log(f"Ingested {raw_count} raw lines. Found {unique_count} unique rules after resolving {conflict_count} conflicts.")

    # 2. 逻辑优化
    sorted_rules = sorted(list(deduped_rules), key=lambda x: (x[0], x[1]))

    # 3. 写入输出
    log(f"Writing to {OUTPUT_FILE}...")
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# --------------------------------------------------------------\n")
        f.write("# ACL4SSR-Neo Merged AD Block List\n")
        f.write(f"# Generated by Smart Build System at {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"# Total Rules: {unique_count}\n")
        f.write(f"# Conflicts Resolved: {conflict_count}\n")
        f.write("# --------------------------------------------------------------\n\n")

        for rtype, rval in sorted_rules:
            f.write(f"{rtype},{rval}\n")

    duration = time.time() - start_time
    log(f"Build completed in {duration:.2f} seconds.")
    log(f"Final output: {OUTPUT_FILE}")
    if conflict_count:
        preview = list(conflict_map.items())[:5]
        for rval, conflict in preview:
            log(f"Resolved conflict for {rval}: kept {conflict['winner']} over {', '.join(conflict['rule_types'])}")


if __name__ == "__main__":
    try:
        build()
    except Exception as e:
        log(f"Fatal Error: {str(e)}")
        sys.exit(1)
